[build]
  publish = "."
  command = "node populate-firebase-config.js"

[context.production]
  publish = "."
  command = "node populate-firebase-config.js"

[context.deploy-preview]
  publish = "/"
  command = "# no build command"

[context.branch-deploy]
  publish = "/"
  command = "# no build command" 